/* sv-läpiajon suomen tunnistin (PURE; docs/CODE_BRIEF_I18N_SV_LAPIAJO.md). Heuristiikka: vahvat suomalaiset sanat + päätteet vs ruotsin yleissanat.
   ÄLÄ kirjoita tähän ruotsia käännöksiksi — SV_SANAT on vain tunnistuslista (väärien osumien estoon). Palauttaa { fi: boolean, pisteet }. */
const FI_SANAT = new Set(('ei tai kun jos että mutta myös vain jo vielä kanssa ilman sekä joka jotka tämä tämän tähän tässä nämä minä sinä meidän teidän sinun minun oma oman omat omia uusi uusia uuden kaikki kaikille kaikkia ensin sitten nyt tänään huomenna eilen viikko viikon viikot viikkoa kuukausi päivä päivän päivää aika ajan jakso jakson jaksolla jaksot jaksoa pelaaja pelaajat pelaajan pelaajia pelaajaa valmentaja valmentajan valmentajat valmentajia harjoitus harjoitukset harjoituksen harjoitteet harjoite harjoitteen tallenna tallennettu tallennetaan peruuta sulje avaa lisää poista muokkaa valitse valittu valitut kirjaa kirjaudu sisään ulos seuraava edellinen takaisin lähetä hae näytä piilota ladataan virhe onnistui epäonnistui tulos tulokset joukkue joukkueen joukkueet joukkueessa seura seuran seurat kausi kauden tavoite tavoitteet tavoitteen ottelu ottelut ottelun testi testit testin kalenteri tapahtuma tapahtumat viesti viestit viestin koti asetukset kortti kortit klo kpl yhteensä tilanne ryhmä ryhmät ryhmän nimi ikä vahvuus vahvuudet vahvuutesi ydinvahvuus kehitys kehityskohde havainto havainnot havainnon arvio arviointi arvioi kysymys kysymykset vastaus vastaukset ohje ohjeet tiedot tieto tyhjä ladataan odottaa odottavat valmis valmista kesken käynnissä päättynyt aloita aloitus jatka hylkää vahvista kuittaa kuittaus kuorma fiilis kirjaus kirjaukset kirjattu harjoittelu omatoiminen pallo jalka maali pelipaikka pelaajaraportti raportti raportointi seuranta ennätys mitali mitta mittaus mittaukset tulossa estynyt paikalla poissa myöhässä ajallaan lähetetty luettu lukematon uusia vanhat vanhempi vanhemmat huoltaja huoltajat perhe lapsi lapsen nuori nuoret kokeile kokeilu ohjelma ohjelmat kirjasto pankki tallennus tämänhetkinen mukana ilmoitus ilmoitukset muistutus muistiinpano muistiinpanot kenelle koko vain jaa jaettu jakaminen kieli kielen selvä selite lisätietoja ehdota ehdotus ehdotukset oletus kuvaus otsikko teksti linkki liite kuva klippi kysy kerro katso katsomaan katsele näet näkyy näkyvissä piilossa vaihda vaihto siirry siirrä kopioi tulosta lataa vie tuo tuonti rivi rivit sarake sarakkeet tiedosto taulukko pohja oikealla vasemmalla jälkeen ennen aikana välillä kunnes alkaen asti mennessä').split(/\s+/));
const SV_SANAT = new Set(('och att det den inte som med till från ett en är vid på om men så nu här där har kan ska skall vill var vara blir bli för av i de du jag vi ni han hon man sin sitt sina din ditt dina vår vårt våra hela alla allt något ingen inga någon några mer mest minst lite bara också eller samt efter innan under över mellan utan genom enligt mot hos kring bland både varje denna detta dessa vilken vilket vilka när hur varför vad vem vart ja nej tack ok idag imorgon igår vecka veckor dag dagar månad år spelare tränare träning lag förening period mål säsong match matcher test meddelande meddelanden kalender hem inställningar kort spara avbryt stäng öppna lägg ta bort redigera välj skicka sök visa dölj laddar fel lyckades misslyckades resultat').split(/\s+/));
// Suomen yhdyssanat: vahva vartalo sanan sisällä (Kotiharjoitteet, Pikakirjaus). Vain ≥6 merkin sanoille.
const FI_VARTALOT = ['harjoit', 'kirjaus', 'kirjaa', 'pelaaj', 'valmenta', 'jakso', 'taido', 'tavoit', 'vahvuu', 'kehity', 'havain', 'arvio', 'tulos', 'testi', 'kalenteri', 'tapahtum', 'viesti', 'ryhm', 'joukkue', 'ottelu', 'asetuks', 'ilmoitu', 'muistiin', 'seuranta', 'mittau', 'ennätys', 'tallenn', 'kirjaudu', 'keho', 'kortti', 'pohja', 'ohjel', 'vanhem', 'huoltaj', 'tekniik', 'kisa', 'kohdenn', 'ydin', 'vahvist', 'valinta', 'signaal', 'tilann', 'sivu'];
const SV_PAATE = /(ning|ningen|heten|else|ande|ende|arna|erna|orna|ska|iska)$/;
const FI_PAATE = /(ssa|ssä|sta|stä|lla|llä|lta|ltä|lle|ksi|nen|ista|istä|ille|issa|issä|iden|tta|ttä|mme|nne|vat|vät|aan|ään|uus|yys|inen|llinen|ton|tön|ois|ois[a-z]{0,2})$/;
const FI_PARIT = /(aa|ee|ii|oo|uu|yy|ää|öö|ie|uo|yö|äi|öi|ai|ei|oi|ui|yi)/;

export function sanat(teksti) { return (String(teksti).toLowerCase().match(/[a-zåäö]+/g) || []); }

export function onkoSuomea(teksti) {
  const t = sanat(teksti); if (!t.length) return { fi: false, pisteet: 0, sv: 0 };
  const kirjaimia = t.join('').length; if (kirjaimia < 3) return { fi: false, pisteet: 0, sv: 0 };
  let vahva = 0, paate = 0, sv = /å/i.test(teksti) ? 2 : 0;
  for (const s of t) {
    if (FI_SANAT.has(s) || (s.length >= 6 && FI_VARTALOT.some((v) => s.indexOf(v) >= 0) && !SV_SANAT.has(s))) vahva++;
    else if (SV_SANAT.has(s)) sv++;
    else if (s.length >= 6 && !SV_PAATE.test(s) && FI_PAATE.test(s) && FI_PARIT.test(s)) paate++;
  }
  const pisteet = vahva * 2 + paate;
  return { fi: pisteet >= 2 && pisteet > sv * 2 - 1, pisteet, sv };
}
